name: ipython-kernel
version: '0.8.3.0'
synopsis: A library for creating kernels for IPython frontends
description: ipython-kernel is a library for communicating with frontends for the
  interactive IPython framework. It is used extensively in IHaskell, the interactive
  Haskell environment.
category: Development
author: Andrew Gibiansky
maintainer: andrew.gibiansky@gmail.com
license: MIT
homepage: http://github.com/gibiansky/IHaskell
dependencies:
- base
- filepath >=1.2
- text >=0.11
library:
  source-dirs: src
  other-extensions:
  - OverloadedStrings
  exposed-modules:
  - IHaskell.IPython.Kernel
  - IHaskell.IPython.Types
  - IHaskell.IPython.ZeroMQ
  - IHaskell.IPython.Message.Parser
  - IHaskell.IPython.Message.UUID
  - IHaskell.IPython.EasyKernel
  dependencies:
  - aeson
  - bytestring >=0.10
  - cereal >=0.3
  - containers >=0.5
  - directory >=1.1
  - interpolate
  - temporary >=1.2
  - process >=1.1
  - unordered-containers >=0.2.5
  - uuid >=1.3
  - zeromq4-haskell >=0.1
  - SHA >=1.6
flags:
  examples:
    description: Build example programs
    manual: false
    default: false
